module.exports = {
  env: {
    NEXT_PUBLIC_LINKEDIN_URL: process.env.LINKEDIN_URL,
    NEXT_PUBLIC_TWITTER_URL: process.env.TWITTER_URL,
    NEXT_PUBLIC_INSTAGRAM_URL: process.env.INSTAGRAM_URL,
    NEXT_PUBLIC_GITHUB_URL: process.env.GITHUB_URL,
    NEXT_PUBLIC_SOHOAPP_URL: process.env.SOHOAPP_URL
  }
}
